### ISSUE TITLE
Infinite requestAnimationFrame loop

### ISSUE THREAD

**Issue by dontwork** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#15] opened 2018-03-05 14:22 UTC
Hey there! 

We noticed a high CPU and GPU draw on a specific area of our product and have pinpointed it to be this plugin.

Specifically this code (line 668 - 697 i think):

```
    _animator: function(time) {
      this._animationCanvasElement.getContext('2d')
        .clearRect(0, 0, this._animationCanvasElement.width, this._animationCanvasElement.height);

      this._drawSelectedCanvasPaths(true); // draw it again to give the appearance of a moving dot with a new lineDashOffset

      TWEEN.update(time);

      this._animationFrameId = L.Util.requestAnimFrame(this._animator, this);
    },
```

if you stick a breakpoint on the line with `L.Util.requestAnimFrame` you will notice when you click play it will keep getting hit endlessly. Essentially it seems like the function this code wants to run on animationFrame fired is triggering an animation frame causing an endless loop.

I wonder if you have any ideas on this issue? Whether this is necessary or whether this can be worked around for less power draw... This CPU and GPU draw is heavy even when there are no animated lines on screen

**Comment by jwasilgeo** [comment] 2018-03-05 17:45
@dontwork this is an interesting find, thanks for reporting it and for providing this information.  Do you have a publicly accessible demo where I could reproduce this issue to help investigate and try to debug?

I agree that, at the very least, this section of the code shouldn't be used when there are no currently animated lines.

**Comment by dontwork** [comment] 2018-03-06 10:34
it happens on sarah's demo (https://sarahbellum.github.io/Canvas-Flowmap-Layer/demos/main/). If you pause within that function highlighted above you will see it get endlessly called.

I don't quite follow exactly what is going on but do you think it is possible to prevent this behaviour?

EDIT: From developing my knowledge a bit further with regard to requestAnimationFrame it seems as though this may be working as intended but its just so intensive. I wonder if theres an alternative animation method that could be used

**Comment by jwasilgeo** [comment] 2018-03-06 15:12
Do I understand that you are seeing this both in the LeafletJS and ArcGIS API for JavaScript versions of this custom layer (this repo and Sarah’s repo, respectively)?

**Comment by dontwork** [comment] 2018-03-07 09:21
Yes, that is correct

**Comment by jwasilgeo** [comment] 2018-03-07 15:38
@dontwork I see what you mean now.  Yes, the requestAnimationFrame is working as intended, but you have shown me a specific case where it should not necessarily be running.

You can play/pause the animations yourself by calling `myLayer.stopAnimation()` (and later, if you want to, `myLayer.playAnimation()`).

https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer#method-summary 

However, when there are no selected origin-destination relationships (i.e. when there are no bezier curves being drawn at all) _and_ when the animation is set to be turned on, the requestAnimationFrame is still running.  For this situation I will add an additional check for this to stop it from happening.

Calling `myLayer.stopAnimation()` should help you out for now until I have the chance to make a code update.  You can also construct and start the layer with `animationStarted: false`.

**Comment by jwasilgeo** [comment] 2018-03-09 15:57
@dontwork the updates are now on `master` branch.  I'll close this issue but please feel free to reopen, comment, etc. if you have any feedback.  Thanks.

**Comment by jwasilgeo** [comment] 2018-03-09 15:58
And, I will make the same updates for the version of this layer that supports the ArcGIS API for JavaScript.

UPDATE: Done, in https://github.com/sarahbellum/Canvas-Flowmap-Layer/commit/6ac9eaee2abf23634a4c01f1df8f16abff026ba3.

**Closed as completed by jwasilgeo** 2018-03-09 15:57 UTC
Labels: bug
